// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxmF5W2Mdo5fJuV50em_SNNi4n5RtYGg',
    appId: '1:784260625960:web:27dbbf51e373ca9f24e71d',
    messagingSenderId: '784260625960',
    projectId: 'schedomeet',
    authDomain: 'schedomeet.firebaseapp.com',
    storageBucket: 'schedomeet.appspot.com',
    measurementId: 'G-ZYYKY7BS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhXbkdzOS4qdRd5CqLhpi88OdZV8kIHis',
    appId: '1:784260625960:android:010d1d44baf9a2d124e71d',
    messagingSenderId: '784260625960',
    projectId: 'schedomeet',
    storageBucket: 'schedomeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiTT2R7-r4if3ibZF8H3InPYxXbWzLgdA',
    appId: '1:784260625960:ios:581adcc09413841b24e71d',
    messagingSenderId: '784260625960',
    projectId: 'schedomeet',
    storageBucket: 'schedomeet.appspot.com',
    iosClientId: '784260625960-tkalpq1hv4fs4un1f9vis995dll8uuo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitPlanner',
  );
}
